Update 71087094.yml

diff --git a/.github/workflows/71087094.yml b/.github/workflows/71087094.yml
--- a/.github/workflows/71087094.yml
+++ b/.github/workflows/71087094.yml
@@ -10,5 +10,4 @@ jobs:
     steps:
       - name: Debug echo
         run: |
-          filename="data/Sales.csv"
-          echo "::error::Filename $filename doesn't match possible files" && exit 1
+          echo "::error file=data/Sales.csv,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon" && exit 1
